// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'photo.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'photo.g.dart';

@freezed
class Photo with _$Photo {
  const factory Photo({
    required int id,
    required String name,
    required String blurhash,
    required String url,
    required String uuid,
    required int storageId,
  }) = _Photo;

  factory Photo.fromJson(Map<String, Object?> json) => _$PhotoFromJson(json);
}

@freezed
class PhotoList with _$PhotoList {
  const factory PhotoList({
    required List<Photo> photos,
    required int filterHash,
  }) = _PhotoList;

  factory PhotoList.fromJson(Map<String, Object?> json) =>
      _$PhotoListFromJson(json);
}

@freezed
class Thumbnail with _$Thumbnail {
  factory Thumbnail({
    required String uuid,
    required String filePath,
    required String url,
  }) = _Thumbnail;
  Thumbnail._();

  factory Thumbnail.fromJson(Map<String, Object?> json) =>
      _$ThumbnailFromJson(json);

  // late final String url =
  //     '${path.replaceFirst('http://', 'https://')}.$extension';
}
