// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {

      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhlyuy0Jp11_xLZbidz9P0qcdzxV4EFOs',
    appId: '1:486178736124:web:24c691d439dcf5f6f3d479',
    messagingSenderId: '486178736124',
    projectId: 'my-family-story-firebase',
    authDomain: 'my-family-story-firebase.firebaseapp.com',
    storageBucket: 'my-family-story-firebase.appspot.com',
    measurementId: 'G-DP5G47352Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6mkBQmK80GLdhZHsMoSD4D8-1BlMpi50',
    appId: '1:486178736124:android:f64034b9ffcef089f3d479',
    messagingSenderId: '486178736124',
    projectId: 'my-family-story-firebase',
    storageBucket: 'my-family-story-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAltVkECUQ55mq331gq94o_0_9kcC-ck',
    appId: '1:486178736124:ios:86eb627b40d2af07f3d479',
    messagingSenderId: '486178736124',
    projectId: 'my-family-story-firebase',
    storageBucket: 'my-family-story-firebase.appspot.com',
    iosClientId: '486178736124-n40qafn5bj136p3u5bpoft2of9ijgm37.apps.googleusercontent.com',
    iosBundleId: 'myfamilystory.best.myFamilyStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAltVkECUQ55mq331gq94o_0_9kcC-ck',
    appId: '1:486178736124:ios:86eb627b40d2af07f3d479',
    messagingSenderId: '486178736124',
    projectId: 'my-family-story-firebase',
    storageBucket: 'my-family-story-firebase.appspot.com',
    iosClientId: '486178736124-n40qafn5bj136p3u5bpoft2of9ijgm37.apps.googleusercontent.com',
    iosBundleId: 'myfamilystory.best.myFamilyStory',
  );
}
